--- 
title: "PhD Toolbox 2018 - Reproducible Research"
author: "Marco Chiapello"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: PhD-Toolbox-course/2018_PhD_Toolbox_course
---

# Preface 

This course material is aimed at people who are already familiar with
the R language and syntax, and who would like to get a hands-on
introduction to reproducible research 

## Caution

This material is currently under development and is likely to change
in the future.

## Installation

A set of packages that are used, either directly or indirectly are
provided in the first chapter. A complete session information with all
packages used to compile this document is available at the end.

The source code for this document is available on GitHub at
https://github.com/PhD-Toolbox-course/2018_PhD_Toolbox_course

A short URL for this book is http://bit.ly/intromlr

## License

This material is licensed under the
[Creative Commons Attribution-ShareAlike 3.0 License](http://creativecommons.org/licenses/by-sa/3.0/). Some
content is inspired by other sources though, see the *Credit* section
in the material.

## Contact 

Feel free to contact me for any question or comments, preferably by
[opening an issue](https://github.com/PhD-Toolbox-course/2018_PhD_Toolbox_course/issues) on
GitHub.


